const courses=[{name:'Computer Basics',desc:'Learn computer fundamentals.'},{name:'Microsoft Word',desc:'Create and format documents.'},{name:'Microsoft Excel',desc:'Learn spreadsheets and formulas.'},{name:'Internet & Email',desc:'Learn internet and online safety.'}];
const defaultNotes=[{course:'Computer Basics',title:'Introduction to Computers',text:'A computer is an electronic device that accepts data, processes it, stores it and produces useful information.\n\nBasic parts include monitor, keyboard, mouse, CPU and storage.'},{course:'Computer Basics',title:'Basic Computer Parts',text:'Monitor displays information. Keyboard is used for typing. Mouse controls the pointer. CPU processes instructions. Storage keeps data.'}];
const getNotes=()=>JSON.parse(localStorage.getItem('gsu_notes')||'null')||defaultNotes;
const getVideos=()=>JSON.parse(localStorage.getItem('gsu_videos')||'[]');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function login(){let e=document.getElementById('email')?.value.trim(),p=document.getElementById('password')?.value.trim();if(!e||!p)return alert('Please enter your email and password.');localStorage.setItem('gsu_user',e);location.href='dashboard.html'}
function logout(){localStorage.removeItem('gsu_user');location.href='index.html'}
function openCourse(n){localStorage.setItem('gsu_course',n);location.href='course.html'}
function go(p){location.href=p}
function loadDashboard(){let e=localStorage.getItem('gsu_user'),el=document.getElementById('studentEmail');if(el)el.textContent=e?'Logged in as: '+e:'Welcome to GSU';let l=document.getElementById('courseList');if(l)l.innerHTML=courses.map(c=>`<div class="item"><h3>${c.name}</h3><p class="muted">${c.desc}</p><button class="btn" onclick="openCourse('${c.name}')">Continue</button></div>`).join('')}
function loadCourse(){let t=document.getElementById('title');if(t)t.textContent=localStorage.getItem('gsu_course')||'Computer Basics'}
function loadNotes(){let c=localStorage.getItem('gsu_course')||'Computer Basics',t=document.getElementById('courseTitle'),l=document.getElementById('notesList');if(t)t.textContent=c+' — Notes';let n=getNotes().filter(x=>!x.course||x.course===c);if(l)l.innerHTML=n.length?n.map(x=>`<div class="item"><h3>${esc(x.title)}</h3><p>${esc(x.text).replace(/\n/g,'<br>')}</p></div>`).join(''):'<p class="muted">No notes yet.</p>'}
function yt(u){try{let x=new URL(u);return x.hostname.includes('youtu.be')?x.pathname.slice(1):x.searchParams.get('v')||''}catch(e){return''}}
function loadVideos(){let c=localStorage.getItem('gsu_course')||'Computer Basics',t=document.getElementById('videoCourse'),l=document.getElementById('videosList');if(t)t.textContent=c+' — Videos';let v=getVideos().filter(x=>!x.course||x.course===c);if(l)l.innerHTML=v.length?v.map(x=>{let id=yt(x.url);return `<div class="item"><h3>${esc(x.title)}</h3>${id?`<div class="video-wrap"><iframe src="https://www.youtube.com/embed/${encodeURIComponent(id)}" allowfullscreen></iframe></div>`:'<p>Invalid YouTube link.</p>'}</div>`}).join(''):'<p class="muted">No videos added yet.</p>'}
function addNote(){let c=document.getElementById('noteCourse')?.value.trim(),t=document.getElementById('noteTitle')?.value.trim(),x=document.getElementById('noteText')?.value.trim();if(!c||!t||!x)return alert('Fill in all note fields.');let n=getNotes();n.push({course:c,title:t,text:x});localStorage.setItem('gsu_notes',JSON.stringify(n));alert('Note saved successfully.');location.href='notes.html'}
function addVideo(){let c=document.getElementById('videoCourse')?.value.trim(),t=document.getElementById('videoTitle')?.value.trim(),u=document.getElementById('videoUrl')?.value.trim();if(!c||!t||!u)return alert('Fill in all video fields.');if(!yt(u))return alert('Enter a valid YouTube URL.');let v=getVideos();v.push({course:c,title:t,url:u});localStorage.setItem('gsu_videos',JSON.stringify(v));alert('Video saved successfully.');location.href='videos.html'}
function submitQuiz(){let a=document.querySelector('input[name=q1]:checked'),b=document.querySelector('input[name=q2]:checked');if(!a||!b)return alert('Please answer all questions.');localStorage.setItem('gsu_score',(Number(a.value)+Number(b.value))*50+'%');location.href='results.html'}
function loadResults(){let e=document.getElementById('score');if(e)e.textContent='Your latest quiz score: '+(localStorage.getItem('gsu_score')||'No result yet.')}
document.addEventListener('DOMContentLoaded',()=>{if(document.getElementById('courseList'))loadDashboard();if(document.getElementById('title'))loadCourse();if(document.getElementById('notesList'))loadNotes();if(document.getElementById('videosList'))loadVideos();if(document.getElementById('score'))loadResults()});